# Example GitHub Actions workflow for deploying the Time Tracking application
# Copy this to .github/workflows/deploy.yml in your repository root

name: Deploy Time Tracking App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Required permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  MAIN_STACK_NAME: ${{ vars.MAIN_STACK_NAME }}
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            infrastructure/package-lock.json
            infrastructure/lambda/*/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && secrets.AWS_PRODUCTION_ROLE_ARN || secrets.AWS_DEVELOPMENT_ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install infrastructure dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Install Lambda dependencies
        run: |
          cd infrastructure/lambda/timeRecords
          npm ci
          cd ../projects
          npm ci
          cd ../profile
          npm ci

      - name: Deploy infrastructure
        run: |
          cd infrastructure
          npm run deploy -- --require-approval never
        env:
          CDK_DEFAULT_ACCOUNT: ${{ steps.configure-aws-credentials.outputs.aws-account-id }}
          CDK_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: Get stack outputs
        id: stack-outputs
        run: |
          cd infrastructure
          OUTPUTS=$(aws cloudformation describe-stacks --stack-name ${{ env.MAIN_STACK_NAME }} --query 'Stacks[0].Outputs' --output json)
          echo "outputs=$OUTPUTS" >> $GITHUB_OUTPUT

    outputs:
      stack-outputs: ${{ steps.stack-outputs.outputs.outputs }}

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && secrets.AWS_PRODUCTION_ROLE_ARN || secrets.AWS_DEVELOPMENT_ROLE_ARN }}
          role-session-name: GitHubActions-Frontend-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Extract amplify_outputs.json from stack outputs
        run: |
          cd frontend
          echo '${{ needs.deploy-infrastructure.outputs.stack-outputs }}' | \
          jq -r '.[] | select(.OutputKey=="AmplifyOutputsJson") | .OutputValue' > public/amplify_outputs.json
          echo "Generated amplify_outputs.json:"
          cat public/amplify_outputs.json

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to S3
        run: |
          cd frontend
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }}/ --delete

      - name: Get CloudFront distribution ID
        id: cloudfront
        run: |
          DISTRIBUTION_ID=$(echo '${{ needs.deploy-infrastructure.outputs.stack-outputs }}' | \
          jq -r '.[] | select(.OutputKey=="WebsiteUrl") | .OutputValue' | \
          sed 's|https://||' | sed 's|\.cloudfront\.net||')
          echo "distribution-id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.cloudfront.outputs.distribution-id }} \
            --paths "/*"

  test-deployment:
    name: Test Deployment
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure, deploy-frontend]
    if: github.ref != 'refs/heads/main'  # Only run tests for non-production deployments
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm test -- --run

      - name: Basic health check
        run: |
          WEBSITE_URL=$(echo '${{ needs.deploy-infrastructure.outputs.stack-outputs }}' | \
          jq -r '.[] | select(.OutputKey=="WebsiteUrl") | .OutputValue')
          
          echo "Testing website at: $WEBSITE_URL"
          
          # Wait for deployment to propagate
          sleep 30
          
          # Basic HTTP check
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WEBSITE_URL")
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Website is accessible (HTTP $HTTP_STATUS)"
          else
            echo "❌ Website returned HTTP $HTTP_STATUS"
            exit 1
          fi